version: '3'

services:
  db:
    container_name: peci-db
    image: postgres:16.2-bookworm
    # volumes:
    #   - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=peci

  backend:
    container_name: peci-backend
    build: ./backend
    depends_on:
      - db
    # volumes:
    #   - ./backend:/backend:ro
    environment:
      - URL_DATABASE=postgresql://postgres:postgres@db:5432/peci
    expose:
      - 8000

  frontend:
    container_name: peci-frontend
    build: ./frontend
    expose:
      - 3000

  nginx:
    container_name: peci-nginx
    build: ./nginx
    depends_on:
      - backend
      - frontend
    ports:
      - "80:80"

# volumes:
#     postgres_data:
